### ISSUE TITLE
change host to bind to?

### ISSUE THREAD

**Issue by cawaker** [LazerUnicorns/node-adblock-proxy#3]
I looked through the code, but in my nodeJS newbie-ness I wasnt able to find the proper place to change the IP address to bind the proxy to.  while 127.0.0.1 is great for local proxy, I was looking to bind it to a different IP for remote vpn/proxy usage.

Thanks.

**Comment by martensms** [comment]
You can set the settings.ispublic = true; Then the proxy is bound locally and listening only on a port, not on a specified address. So, for example, you can install the proxy on a different device and use that as a gateway via its LAN IP (e.g. using 192.168.1.123:8080 in the proxy settings of your machine).

You just need to modify this line here and add "ispublic: true," to it:
https://github.com/LazerUnicorns/node-adblock-proxy/blob/master/start.js#L41

I think it might make sense to add more settings to the command line interface, so that you can use "./proxy.sh <ip>:<port> --public=true" or similar.

**Comment by martensms** [comment]
Also: Note that HTTPS is currently not supported. It might take a while, I had the idea of having a deep-inspection type proxy where also SSL-encrypted ads are filtered. So the "secure" connection to Facebook or other third party sites would be like:

third party <encrypted with their cert> proxy <encrypted with proxy cert> client

**Comment by cawaker** [comment]
Awesome thanks!

**Comment by martensms** [comment]
You're welcome ;)
